[package]
name = "nihao-usb"
version = "0.1.0"
authors = ["luojia65 <me@luojia.cc>"]
edition = "2018"

[dependencies]

[target.'cfg(windows)'.dependencies.winapi]
version = "*"
features = ["winusb", "setupapi", "handleapi", "errhandlingapi", "winerror", "usbiodef", "winbase"]
